### PR TITLE
Update search pattern for import position

### LINKED ISSUE #18: Generate screen
```
$ ignite generate screen Activity

✔︎ App/Containers/ActivityScreen.js
✔︎ App/Containers/Styles/ActivityScreenStyle.js
vvv -----[ DEBUG ]----- vvv
Error: 'import { StackNavigator } from' was not found in file ./App/Navigation/AppNavigation.js.
    at Object.insertInFile (/Users/rwoverdijk/.nvm/versions/node/v7.8.0/lib/node_modules/ignite-cli/src/extensions/patching.js:31:33)
    at Object.patchInFile (/Users/rwoverdijk/.nvm/versions/node/v7.8.0/lib/node_modules/ignite-cli/src/extensions/ignite/patchInFile.js:44:16)
    at Object.module.exports [as run] (./node_modules/ignite-ir-next/commands/screen.js:48:12)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
^^^ -----[ DEBUG ]----- ^^^
```

Which makes sense. I implemented Redux in my app (sort of, still trying) so the import line looks like this:

```js
import {StackNavigator, addNavigationHelpers} from 'react-navigation';
```

If this is regex, maybe just look for `from 'react-navigation';` instead. It doesn't matter what gets imported.

### PR DESCRIPTION
**Pull request by RWOverdijk**
Not sure if this thing works with regex or not... The regex works anyway: https://regex101.com/r/ihSFX1/2

Fixes #18 (tries to, anyway)

### CODE REVIEW

**Comment by GantMan** [comment]
regex should work here, bc it gets thrown into regex anyway.  I def want to test before merge, though.

**Comment by RWOverdijk** [comment]
Wise :)

**Comment by GantMan** [comment]
Also @RWOverdijk - you may be wondering how I tested this.  I used your branch on my local machine.  You can easily test this like so:

image

**Comment by GantMan** [comment]
can you add the changes to the 2 other files?

**Comment by RWOverdijk** [comment]
Ah! I missed those... I didn't read

**Comment by RWOverdijk** [comment]
I'll open up a new PR. In any case, I'd probably make a central "instruction" class that handles stuff like `.addRoute()` as it's duplicate now. Also I'd change the route pattern, as I noticed that also doesn't work for me anymore. Maybe leave it up to the user of the project to define their own pattens (make it configurable) so it can grow _with_ the project. Not now, though, because I don't have time atm.

**Comment by jamonholmgren** [comment]
#22 is new PR, for future reference here.

**Pull request closed without merging**
